version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
    commit-message:
      prefix: deps
      include: scope

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    commit-message:
      prefix: deps
      include: scope

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    commit-message:
      prefix: deps
      include: scope

  - package-ecosystem: "docker"
    directory: "/deployments"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
    commit-message:
      prefix: deps
      include: scope
